"""
Report Generator - Produces downloadable executive PDF reports using reportlab.
"""
import io
import base64
import textwrap
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, ListFlowable, ListItem,
)


class ReportGenerator:
    """Generates a professional PDF report from analysis data."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        self.styles.add(ParagraphStyle(
            name="ADAA_Title",
            parent=self.styles["Title"],
            fontSize=22,
            textColor=colors.HexColor("#1a1a2e"),
            spaceAfter=10,
        ))
        self.styles.add(ParagraphStyle(
            name="ADAA_Subtitle",
            parent=self.styles["Normal"],
            fontSize=11,
            textColor=colors.HexColor("#444"),
            spaceAfter=20,
        ))
        self.styles.add(ParagraphStyle(
            name="ADAA_Heading",
            parent=self.styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#89b4fa"),
            spaceBefore=12,
            spaceAfter=6,
        ))
        self.styles.add(ParagraphStyle(
            name="ADAA_Body",
            parent=self.styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#222"),
        ))
        self.styles.add(ParagraphStyle(
            name="ADAA_Bullet",
            parent=self.styles["Normal"],
            fontSize=10,
            leading=14,
            leftIndent=12,
            bulletIndent=2,
            spaceAfter=4,
        ))

    def generate_pdf(self, report_data):
        """Generate a PDF byte stream from executive report data."""
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            rightMargin=0.75 * inch, leftMargin=0.75 * inch,
            topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        )
        story = []

        # Title
        title = report_data.get("title", "Executive Data Analysis Report")
        story.append(Paragraph(title, self.styles["ADAA_Title"]))
        story.append(Paragraph(
            f"Generated by {report_data.get('generated_from', 'Auto Data Analyst Agent')} "
            f"on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            self.styles["ADAA_Subtitle"],
        ))
        story.append(Spacer(1, 6))

        # Overview section
        overview = report_data.get("overview", {})
        if overview:
            story.append(Paragraph("1. Dataset Overview", self.styles["ADAA_Heading"]))
            overview_rows = [
                ["Attribute", "Value"],
                ["Dataset", str(overview.get("dataset", ""))],
                ["Rows", str(overview.get("rows", ""))],
                ["Columns", str(overview.get("columns", ""))],
                ["Numeric Columns", ", ".join(overview.get("numeric_columns", []))],
                ["Categorical Columns", ", ".join(overview.get("categorical_columns", []))],
                ["Missing Values", str(overview.get("missing_values", ""))],
                ["Duplicate Rows", str(overview.get("duplicate_rows", ""))],
            ]
            t = Table(overview_rows, colWidths=[2.2 * inch, 4.0 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#89b4fa")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f7ff")]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

        # Key metrics
        metrics = report_data.get("metrics", {})
        if metrics:
            story.append(Paragraph("2. Key Metrics", self.styles["ADAA_Heading"]))
            metric_rows = [["Column", "Total", "Average", "Min", "Max"]]
            for col, m in metrics.items():
                metric_rows.append([
                    str(col),
                    f"{m.get('total', 0):,.2f}",
                    f"{m.get('average', 0):,.2f}",
                    f"{m.get('min', 0):,.2f}",
                    f"{m.get('max', 0):,.2f}",
                ])
            t = Table(metric_rows, colWidths=[1.6 * inch, 1.4 * inch, 1.4 * inch, 1.2 * inch, 1.2 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f38ba8")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff5f7")]),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

        # Insights
        insights = report_data.get("insights", {})
        if insights:
            story.append(Paragraph("3. Key Findings", self.styles["ADAA_Heading"]))
            findings = insights.get("findings", [])
            if findings:
                bullets = [Paragraph(f"• {f}", self.styles["ADAA_Body"]) for f in findings]
                story.extend(bullets)

            drivers = insights.get("key_drivers", [])
            if drivers:
                story.append(Paragraph("Key Drivers", self.styles["ADAA_Heading"]))
                story.append(Paragraph(", ".join(drivers), self.styles["ADAA_Body"]))
                story.append(Spacer(1, 6))

            anomalies = insights.get("anomalies", [])
            if anomalies:
                story.append(Paragraph("Detected Anomalies", self.styles["ADAA_Heading"]))
                for a in anomalies:
                    story.append(Paragraph(
                        f"• Column '{a.get('column', '')}': {a.get('count', 0)} outlier(s)",
                        self.styles["ADAA_Body"],
                    ))
                story.append(Spacer(1, 6))

        # Recommendations
        recommendations = insights.get("recommendations", []) if insights else []
        if recommendations:
            story.append(Paragraph("4. Recommendations", self.styles["ADAA_Heading"]))
            for r in recommendations:
                story.append(Paragraph(f"• {r}", self.styles["ADAA_Body"]))

        story.append(Spacer(1, 12))
        story.append(Paragraph(
            "— End of report. Generated automatically by the Auto Data Analyst Agent.",
            self.styles["ADAA_Subtitle"],
        ))

        doc.build(story)
        buf.seek(0)
        return buf.read()

    def pdf_to_base64(self, report_data):
        """Generate PDF and return as base64 string."""
        pdf_bytes = self.generate_pdf(report_data)
        return base64.b64encode(pdf_bytes).decode("utf-8")
